services:
  tv-reomote:
    build: .
    container_name: tv-reomote
    restart: unless-stopped
    network_mode: host
    environment:
      BROWSER_CDP_URL: http://127.0.0.1:9222
      HOME_URL: https://www.youtube.com/
